version: "3.8"

services:
  api:
    build:
      context: ./docker/images/node
    container_name: tcc_api
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    working_dir: /app
    command: node helloWorld.js
