name: API

on:
  push:
    branches: [ api ]
  pull_request:
    branches: [ api ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16.*

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test tests/User.test.ts
